### ISSUE TITLE
Warn when second user attempts to dig a tunnel which supports single user only

### ISSUE THREAD

**Issue by DMIII** [calmh/mole#69]
There are tunnels which could be used only by single user at a time.

If User B digs such tunnel when User A is already using it, User A gets disconnected.
Once disconnected, User A tries to dig the tunnel again which in turn disconnects User B.
And then again and again in loop.

It would be really nice to have some warning like:
```
$ ./mole dig zzz

warning: Tunnel "zzz" supports single user mode only. User "xxx" already uses "zzz".
         Please run with --force flag to override.
```

**Comment by calmh** [comment]
There is no way in general for the server to know which tunnels are active on clients.

**Comment by DMIII** [comment]
So there is no chance to have this implemented?

**Comment by calmh** [comment]
No.
